services:
  app:
    container_name: go-app
    build: ./
    command: ./medods-task
    environment:
      - DB_HOST=db
      
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./cmd/.env
  
  db:
    container_name: postgres_container
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1998
      POSTGRES_DB: medods_task
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/migration/up.sql:/docker-entrypoint-initdb.d/up.sql:ro
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d medods_task"]
      interval: 5s
      timeout: 5s
      retries: 5
